repos:
- repo: https://github.com/igorshubovych/markdownlint-cli
  rev: v0.31.0
  hooks:
  - id: markdownlint
    exclude: ^(_site/|README.md)
  - id: markdownlint-fix
    exclude: ^(_site/|README.md)
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.1.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-json
- repo: https://github.com/pre-commit/mirrors-eslint
  rev: v8.9.0
  hooks:
  - id: eslint
    exclude: ^(_site/|README.md|public/reveal.js)
- repo: https://github.com/pre-commit/mirrors-jshint
  rev: v2.13.4
  hooks:
  - id: jshint
    exclude: ^(_site/|README.md|public/reveal.js)
