# Permalinks
permalink: pretty

# reveal options
reveal:
  slide_separator: "<hr />"
  vertical_separator: "<p>~~</p>"
  notes_separator: "<p>Notes:</p>"
  title_slide: true

# Setup
title: Talks
tagline: "My public talks organized into one place."
description: "My public talks organized into one place."
url: http://r0x0d.github.io/talks
baseurl: /talks
markdown: kramdown
kramdown:
  input: GFM

collections:
  slides:
    output: true
    permalink: /:collection/:title/

# About/contact
author:
  name: Rodolfo Olivieri
  url: https://twitter.com/r0x0d
  email: rodolfo.olivieri3@gmail.com

# YAML defaults
defaults:
  - scope:
      path: ""
      type: slides
    values:
      layout: slides
