#!/bin/env sh

# Original script made by Sebastian Werner <s.werner@sebastian-software.de>
# https://gist.github.com/devongovett/10399980
# Modifications to the script made by Rodolfo Olivieri <rodolfo.olivieri3@gmail.com>

pull_request() {
  to_branch=$1
  if [ -z $to_branch ]; then
    to_branch="main"
  fi

  # try the upstream branch if possible, otherwise origin will do
  origin=$(git config --get remote.origin.url)
  upstream=$origin

  to_user=$(echo $upstream | sed -e 's/.*[\/:]\([^/]*\)\/[^/]*$/\1/')
  from_user=$(echo $origin | sed -e 's/.*[\/:]\([^/]*\)\/[^/]*$/\1/')
  repo=$(basename `git rev-parse --show-toplevel`)
  from_branch=$(git rev-parse --abbrev-ref HEAD)

  xdg-open "https://github.com/$to_user/$repo/pull/new/$to_user:$to_branch...$from_user:$from_branch"
}

# usage
pull_request              # PR to master
